# 워크플로우의 이름을 설정합니다.
name: Update README

# 이 워크플로우가 어떤 이벤트에 의해 실행될지를 지정합니다. 여기서는 push 이벤트에 의해 실행됩니다.
on: [push]

# 이 워크플로우에서 수행할 작업들을 정의합니다.
jobs:
  # 각 작업에는 고유한 ID를 지정합니다. 여기서는 'update-readme'라는 ID를 사용합니다.
  update-readme:
    runs-on: ubuntu-latest

    # 이 작업에서 수행할 단계들을 정의합니다.
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}  # use the PAT

    - name: Pull latest changes
      run: |
        git pull

    - name: Generate directory list and update README
      run: |
        echo "# Directory List" > README.md
        for d in */; do
          echo "- $d" >> README.md
        done

    - name: Commit and push if changed
      run: |
        git diff
        git config --local user.email "ptuguitar@naver.com"
        git config --local user.name "isGeekCode"
        git add -A
        git commit -m "Update README with directory list" -a || exit 0
        git push
